#!/usr/bin/env python

import os
import time

import boto3

from botocore.exceptions import ClientError


def upload_to_s3():
    s3 = boto3.resource("s3")
    data = open("resume.html", "r").read()
    try:
        s3.Bucket(os.getenv("S3_BUCKET")).put_object(
            Body=data, Key="resume.html", ContentType="text/html"
        )
    except ClientError as e:
        print(e)
        exit(1)
    return


def invalidate_cache():
    cf = boto3.client("cloudfront")
    cf.create_invalidation(
        DistributionId=os.getenv("CF_DISTRO_ID"),
        InvalidationBatch={
            "Paths": {"Quantity": 1, "Items": ["/resume.html"]},
            "CallerReference": str(int(time.time())),
        },
    )


def main():
    upload_to_s3()
    print("file uploaded")
    invalidate_cache()
    print("cloudfront invalidating, will complete shortly")
    return


if __name__ == "__main__":
    main()
